// Code generated by "stringer -type=CID"; DO NOT EDIT.

package fragmentation

import "strconv"

const (
	_CID_name_0 = "PackageVersionReqFragSessionStatusReqFragSessionSetupReqFragSessionDeleteReq"
	_CID_name_1 = "DataFragment"
)

var (
	_CID_index_0 = [...]uint8{0, 17, 37, 56, 76}
)

func (i CID) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _CID_name_0[_CID_index_0[i]:_CID_index_0[i+1]]
	case i == 8:
		return _CID_name_1
	default:
		return "CID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
