// Code generated by "stringer -type=CID"; DO NOT EDIT.

package firmwaremanagement

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PackageVersionReq-0]
	_ = x[PackageVersionAns-0]
	_ = x[DevVersionReq-1]
	_ = x[DevVersionAns-1]
	_ = x[DevRebootTimeReq-2]
	_ = x[DevRebootTimeAns-2]
	_ = x[DevRebootCountdownReq-3]
	_ = x[DevRebootCountdownAns-3]
	_ = x[DevUpgradeImageReq-4]
	_ = x[DevUpgradeImageAns-4]
	_ = x[DevDeleteImageReq-5]
	_ = x[DevDeleteImageAns-5]
}

const _CID_name = "PackageVersionReqDevVersionReqDevRebootTimeReqDevRebootCountdownReqDevUpgradeImageReqDevDeleteImageReq"

var _CID_index = [...]uint8{0, 17, 30, 46, 67, 85, 102}

func (i CID) String() string {
	if i >= CID(len(_CID_index)-1) {
		return "CID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CID_name[_CID_index[i]:_CID_index[i+1]]
}
