// Code generated by "stringer -type=CID"; DO NOT EDIT.

package lorawan

import "strconv"

const (
	_CID_name_0 = "ResetIndLinkCheckReqLinkADRReqDutyCycleReqRXParamSetupReqDevStatusReqNewChannelReqRXTimingSetupReqTXParamSetupReqDLChannelReqRekeyIndADRParamSetupReqDeviceTimeReqForceRejoinReqRejoinParamSetupReqPingSlotInfoReqPingSlotChannelReq"
	_CID_name_1 = "BeaconFreqReq"
	_CID_name_2 = "DeviceModeInd"
)

var (
	_CID_index_0 = [...]uint8{0, 8, 20, 30, 42, 57, 69, 82, 98, 113, 125, 133, 149, 162, 176, 195, 210, 228}
)

func (i CID) String() string {
	switch {
	case 1 <= i && i <= 17:
		i -= 1
		return _CID_name_0[_CID_index_0[i]:_CID_index_0[i+1]]
	case i == 19:
		return _CID_name_1
	case i == 32:
		return _CID_name_2
	default:
		return "CID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
