// Code generated by "stringer -type=DeviceModeIndClass"; DO NOT EDIT.

package lorawan

import "strconv"

const _DeviceModeIndClass_name = "DeviceModeIndClassADeviceModeIndRFUDeviceModeIndClassC"

var _DeviceModeIndClass_index = [...]uint8{0, 19, 35, 54}

func (i DeviceModeIndClass) String() string {
	if i >= DeviceModeIndClass(len(_DeviceModeIndClass_index)-1) {
		return "DeviceModeIndClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceModeIndClass_name[_DeviceModeIndClass_index[i]:_DeviceModeIndClass_index[i+1]]
}
