// Code generated by "stringer -type=DeviceModeClass"; DO NOT EDIT.

package lorawan

import "strconv"

const _DeviceModeClass_name = "DeviceModeClassADeviceModeRFUDeviceModeClassC"

var _DeviceModeClass_index = [...]uint8{0, 16, 29, 45}

func (i DeviceModeClass) String() string {
	if i >= DeviceModeClass(len(_DeviceModeClass_index)-1) {
		return "DeviceModeClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceModeClass_name[_DeviceModeClass_index[i]:_DeviceModeClass_index[i+1]]
}
