// Code generated by "stringer -type=JoinType"; DO NOT EDIT.

package lorawan

import "strconv"

const (
	_JoinType_name_0 = "RejoinRequestType0RejoinRequestType1RejoinRequestType2"
	_JoinType_name_1 = "JoinRequestType"
)

var (
	_JoinType_index_0 = [...]uint8{0, 18, 36, 54}
)

func (i JoinType) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _JoinType_name_0[_JoinType_index_0[i]:_JoinType_index_0[i+1]]
	case i == 255:
		return _JoinType_name_1
	default:
		return "JoinType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
