// Code generated by "stringer -type=mType"; DO NOT EDIT

package lorawan

import "fmt"

const (
	_mType_name_0 = "JoinRequest"
	_mType_name_1 = "JoinAccept"
	_mType_name_2 = "UnconfirmedDataUp"
	_mType_name_3 = "UnconfirmedDataDown"
	_mType_name_4 = "ConfirmedDataUp"
	_mType_name_5 = "ConfirmedDataDown"
	_mType_name_6 = "Proprietary"
)

var (
	_mType_index_0 = [...]uint8{0, 11}
	_mType_index_1 = [...]uint8{0, 10}
	_mType_index_2 = [...]uint8{0, 17}
	_mType_index_3 = [...]uint8{0, 19}
	_mType_index_4 = [...]uint8{0, 15}
	_mType_index_5 = [...]uint8{0, 17}
	_mType_index_6 = [...]uint8{0, 11}
)

func (i mType) String() string {
	switch {
	case i == 0:
		return _mType_name_0
	case i == 32:
		return _mType_name_1
	case i == 64:
		return _mType_name_2
	case i == 96:
		return _mType_name_3
	case i == 128:
		return _mType_name_4
	case i == 160:
		return _mType_name_5
	case i == 224:
		return _mType_name_6
	default:
		return fmt.Sprintf("mType(%d)", i)
	}
}
